# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(blank=True, null=True)),
                ('url', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndexedUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=200)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('domain', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(verbose_name='date crawded')),
            ],
        ),
        migrations.DeleteModel(
            name='Keywords',
        ),
    ]
